server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mariadb://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  webflux:
    client:
      connect-timeout: 5000
      read-timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-auth0-domain.auth0.com/
          jwk-set-uri: https://your-auth0-domain.auth0.com/.well-known/jwks.json
          audience: your-api-audience-identifier
  # Use Log4j2 for logging (configured in log4j2.xml)
  main:
    banner-mode: off
    log-startup-info: true

# External services configuration
service:
  inventory:
    baseUrl: http://inventory-service
    apiPath: /api/inventory

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      payment:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
      inventory:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
      payment_gateway:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 40
        automaticTransitionFromOpenToHalfOpenEnabled: true
  bulkhead:
    instances:
      payment:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms
      inventory:
        maxConcurrentCalls: 15
        maxWaitDuration: 500ms
      payment_gateway:
        maxConcurrentCalls: 10
        maxWaitDuration: 1s
  retry:
    instances:
      payment:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
      inventory:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
      payment_gateway:
        maxAttempts: 2
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
  timelimiter:
    instances:
      payment:
        timeoutDuration: 5s
        cancelRunningFuture: true
      inventory:
        timeoutDuration: 3s
        cancelRunningFuture: true
      payment_gateway:
        timeoutDuration: 10s
        cancelRunningFuture: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG 